### ISSUE TITLE
Support protocol buffer exposition format

### ISSUE THREAD

**Issue by pharaujo** [metalmatze/prom-metric-viewer#3]
Prometheus implements two different wire formats: protobuf and plain text (https://prometheus.io/docs/instrumenting/exposition_formats/).

Using prom-metric-viewer 0.1 against a custom exporter that doesn't support the plain text format crashes it:

```
panic: runtime error: index out of range

goroutine 1 [running]:
main.parseRawMetric(0xc4203c6088, 0x2, 0x2, 0x1000, 0xc4203c6088, 0x2, 0x1)
	/go/src/github.com/metalmatze/prom-metric-viewer/main.go:281 +0x2ca
main.parseMetrics(0x19fe078, 0xc4203c4100, 0xc4203c4100, 0x19fe078, 0xc4203c4100, 0x0, 0xc42001a600)
	/go/src/github.com/metalmatze/prom-metric-viewer/main.go:250 +0x343
main.HTTPMetrics(0x7fff5fbff8f4, 0x2d, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/metalmatze/prom-metric-viewer/main.go:229 +0x1dc
main.ViewAction(0xc4200d0140, 0x0, 0x0)
	/go/src/github.com/metalmatze/prom-metric-viewer/main.go:84 +0x1a8
github.com/metalmatze/prom-metric-viewer/vendor/github.com/urfave/cli.HandleAction(0x1348c60, 0x152f010, 0xc4200d0140, 0x0, 0x0)
	/go/src/github.com/metalmatze/prom-metric-viewer/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/metalmatze/prom-metric-viewer/vendor/github.com/urfave/cli.(*App).Run(0xc420001a00, 0xc42000e2d0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/metalmatze/prom-metric-viewer/vendor/github.com/urfave/cli/app.go:259 +0x70d
main.main()
	/go/src/github.com/metalmatze/prom-metric-viewer/main.go:61 +0x2ac
```

I understand you don't need to support custom exporters but it would be more efficient to use the protobuf format for this type of communication.

**Comment by metalmatze** [comment]
Yep. I saw that implementing prom-metric-viewer. 
Seems like they also expose type & help: [metrics.proto](https://github.com/prometheus/client_model/blob/086fe7ca28bde6cec2acd5223423c1475a362858/metrics.proto#L76-%20%20L81).
Personally, I'm not that interested in supporting that format. But we could for sure talk about merging some kind of implementation to support it. :blush:

**Comment by pharaujo** [comment]
Trying out the new github app, and noticed this is still open.

The protobuf exposition format has long been deprecated, so this isn’t relevant anymore 🙂 

Closing.
